'use client';

import { motion } from 'motion/react';
import { FileText, Scale, AlertTriangle, Mail } from 'lucide-react';

export function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
        <div className="flex items-center gap-3 mb-3">
          <div className="p-2 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-lg">
            <FileText className="w-6 h-6 text-white" />
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold">Terms & Conditions</h1>
        </div>
        <p className="text-slate-400">Last updated: June 4, 2026</p>
      </motion.div>

      <div className="rounded-2xl border border-amber-400/30 bg-amber-500/10 p-5 mb-8 flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 text-amber-300 mt-0.5 shrink-0" />
        <div className="text-sm text-amber-100">
          By accessing or using Churnly AI you agree to these Terms. If you are accepting on behalf of a company, you confirm you have the authority to bind that organization.
        </div>
      </div>

      {/* TOC */}
      <div className="rounded-2xl border border-white/10 bg-slate-900/60 backdrop-blur-xl p-5 mb-8">
        <h2 className="font-semibold mb-3 flex items-center gap-2"><Scale className="w-4 h-4 text-indigo-300" /> Contents</h2>
        <ol className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5 list-decimal list-inside text-sm text-slate-300">
          {sections.map((s, i) => (
            <li key={i}><a href={`#s-${i}`} className="hover:text-white">{s.title}</a></li>
          ))}
        </ol>
      </div>

      <div className="space-y-6">
        {sections.map((s, i) => (
          <motion.section
            key={i}
            id={`s-${i}`}
            initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            transition={{ delay: i * 0.04 }}
            className="rounded-2xl border border-white/10 bg-slate-900/60 backdrop-blur-xl p-6"
          >
            <h2 className="font-semibold text-lg mb-3">{i + 1}. {s.title}</h2>
            <div className="space-y-3 text-slate-300 text-sm leading-relaxed">
              {s.body.map((p, j) => <p key={j}>{p}</p>)}
              {s.list && (
                <ul className="list-disc list-inside space-y-1.5 text-slate-400 ml-1">
                  {s.list.map((l, k) => <li key={k}>{l}</li>)}
                </ul>
              )}
            </div>
          </motion.section>
        ))}
      </div>

      <div className="mt-10 rounded-2xl border border-indigo-400/30 bg-gradient-to-br from-indigo-600/15 to-purple-600/5 p-6 flex flex-col sm:flex-row sm:items-center gap-4">
        <Mail className="w-6 h-6 text-indigo-300" />
        <div className="flex-1">
          <div className="font-semibold">Questions about these terms?</div>
          <div className="text-sm text-slate-400">Reach our legal team at legal@churnly.ai.</div>
        </div>
      </div>
    </div>
  );
}

const sections = [
  { title: 'Acceptance of terms', body: ['These Terms govern your access to and use of the Churnly AI service, including any associated software, APIs, and documentation. By using the service, you agree to be bound by these Terms.'] },
  { title: 'Account responsibilities', body: ['You are responsible for safeguarding your account credentials and for any activity under your account. You must notify us immediately of any unauthorized use.'] },
  { title: 'Acceptable use', body: ['You agree not to misuse the service.'], list: [
    'Do not attempt to reverse engineer, decompile, or extract the underlying models.',
    'Do not upload data you do not have the legal right to process.',
    'Do not use the service to make automated decisions that have legal effects on individuals without human review.',
  ] },
  { title: 'Subscriptions and billing', body: ['Paid plans renew automatically at the end of each billing cycle unless cancelled. Fees are non-refundable except where required by law.'] },
  { title: 'Customer data', body: ['You retain all rights to data you submit. You grant Churnly AI a limited license to process that data solely to provide the service to you, in line with our Privacy Policy.'] },
  { title: 'Intellectual property', body: ['The service, including all software, models, and documentation, is owned by Churnly AI and protected by intellectual property law. We grant you a limited, non-exclusive, non-transferable license to use it during your subscription.'] },
  { title: 'AI predictions disclaimer', body: ['Predictions generated by Churnly AI are statistical estimates and may be incorrect. You are solely responsible for the decisions you make based on them and must not use the service as the sole basis for material decisions affecting individuals.'] },
  { title: 'Warranties and limitation of liability', body: ['The service is provided on an "as-is" basis. To the maximum extent permitted by law, Churnly AI disclaims all implied warranties. In no event will our aggregate liability exceed the fees paid by you in the twelve months preceding the claim.'] },
  { title: 'Indemnification', body: ['You agree to indemnify Churnly AI against any third-party claims arising from your misuse of the service or violation of these Terms.'] },
  { title: 'Termination', body: ['Either party may terminate the agreement with thirty days written notice. We may suspend access immediately if you materially breach these Terms.'] },
  { title: 'Governing law', body: ['These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-law principles. Disputes will be resolved exclusively in the courts of Delaware.'] },
  { title: 'Changes to terms', body: ['We may update these Terms periodically. We will notify workspace owners by email at least 30 days before material changes take effect.'] },
];
